apiVersion: apps/v1
kind: Deployment
metadata:
  name: fortune-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fortune
  template:
    metadata:
      labels:
        app: fortune
    spec:
      containers:
        - name: fortune-container
          image: your-dockerhub-username/fortune-telling:latest
          ports:
            - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: fortune-service
spec:
  type: LoadBalancer
  selector:
    app: fortune
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080